- android_quickbrick_app/build.gradle
- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/ReactPackagesManager.java
- rake/templates/package.json.erb
- rake/templates/qb_build.gradle.erb
- rake/templates/qb_settings.gradle.erb
- spec/fixtures/files/external_projects_settings.gradle
- spec/fixtures/files/qb_external_projects_settings.gradle
This PR is adding native dependencies for ViewPager package
> feat: Add react-community-viewpager package

- rake/tasks/quickbrick.rake
- rake/templates/package.json.erb
- spec/tasks/quickbrick_spec.rb
This PR adds the option to build a non minified version of the rn bundle, or even to skip the RN bundle creation step altogether
> feat: add option to build non minified RN bundle

- .circleci/config.yml
- rake/tasks/quickbrick.rake
- spec/tasks/quickbrick_spec.rb
This PR updates the env vars to be lowercase, and checks these env vars to set the proper build flag when building the app in CI
> fix: update env vars

- android_quickbrick_app/src/main/java/com/applicaster/ui/utils/AppConstants.java
- rake/lib/template_helper.rb
- rake/templates/applicaster.properties.erb
Pass to QB missing Device ID and Rivers ID variables required by analytics
> Zapp app missing analytics values

- android_quickbrick_app/src/main/java/com/applicaster/ui/utils/AppConstants.java
add build version for analytics events.
> feat: add build version for analytics events

- android_quickbrick_app/build.gradle
- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/ReactPackagesManager.java
- rake/templates/app_proguard-rules.pro
- rake/templates/package.json.erb
- rake/templates/qb_settings.gradle.erb
- spec/fixtures/files/qb_external_projects_settings.gradle
Ticket: https://applicaster.atlassian.net/browse/TPS-397
Added npm dependencies and linked with the app
- react-native-fast-image
- react-native-linear-gradient
- react-native-svg  
> feat: Add qb native dependencies

- rake/templates/app_proguard-rules.pro
- Adding proguard rule for react-native-linear-gradient and react-native-svg modules
> feat: added proguard rule for linear gradinet and svg

- android_quickbrick_app/build.gradle
- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/QuickBrickManager.java
- gradle.properties
Enable SSL pinning for React Native using SSL pinning plugin
> Feat update Core SDK to 6.4.0 with SSL pinning support

- rake/lib/template_helper.rb
- spec/lib/template_helper_spec.rb
Update default QuickBrick SDK to 4.1.0
> Feat: update default QuickBrick SDK to 4.1.0

- rake/lib/template_helper.rb
- spec/lib/template_helper_spec.rb
set default QuickBrick SDK version to 4.1.1
> Feat: set default QuickBrick SDK version to 4.1.1

- android_quickbrick_app/src/main/java/com/applicaster/ui/activities/MainActivity.java
Intents from Firebase Push messages if handled in the background, will deliver url in the extras, not data.
Now we check it and update the intent data.
> Feat: option to override start intent data with url extra

- android_quickbrick_app/src/main/java/com/applicaster/ui/activities/MainActivity.java
Improve routing for url extra for Firebase push messages for the scenario, when notification was received when the app was not running, then user has launched the app, and only then clicked on the notification.
Also abort launch after routing, if uri scheme did not belong to our application (i.e. another application was expected to be launched), as discussed in https://applicaster.atlassian.net/browse/ZPP-2949.
> Feat: improve Firebase push message url routing

- android_quickbrick_app/src/main/java/com/applicaster/ui/utils/AppConstants.java
This PR adds the `isTabletPortrait` flag in app Data
> feat: add isTabletPortrait flag in AppData

- gradle.properties
+ upgrade core SDK version to 7.0.0 https://github.com/applicaster/applicaster-android-sdk/releases/tag/7.0.0
+ add Glide and Firebase BoM versions to root project properties so plugins can use it
> feat: upgrade core SDK version to 7.0.0

- CHANGELOG.md
Missing changelog for first official QuibkBrick release
> feat: changelog for 1.0.0

- Gemfile.lock
Update appcenter plugin due to old API deprecation
> feat: update fastlane-plugin-appcenter to 1.11.0

- rake/lib/template_helper.rb
- spec/lib/template_helper_spec.rb
Update QuickBrick SDK to latest stable 4.1.2
> feat: update QuickBrick SDK to 4.1.2

- CHANGELOG.md
Change log for patch release 1.0.1
> chore: 1.0.1 patch changelog

- rake/lib/template_helper.rb
- spec/lib/template_helper_spec.rb
Bump SDK default QuickBrick version to 4.1.4
> feat: bump SDK default QuickBrick version to 4.1.4

- android_quickbrick_app/src/main/java/com/applicaster/ui/utils/AppConstants.java
- gradle.properties
Pass device locale data to the QuickBrick communication module to match iOS.
> fix: pass device locale data to the QuickBrick communication module

- CHANGELOG.md
> feat: changelog for 2.0.0

- android_quickbrick_app/src/main/java/com/applicaster/ui/activities/MainActivity.kt
Log important events about app orientation.
> feat: log UI orientation events

- android_quickbrick_app/src/main/java/com/applicaster/ui/activities/MainActivity.kt
Log stack depth so it's easier to detect disparities.
> feat: log stack orientation depth for orientation changes

- gradle.properties
Picking up latest core additions:
- Plugin LocalizationHelper
- New LocalStorage methods: remove, getNamespace, removeNamespace
> feat: update applicaster_android_sdk_core_version to 8.1.0

- rake/templates/app_proguard-rules.pro
Universal proguard rule to keep all analytics plugin implementations by default.
> feat: Add proguard rule for all analytics plugins

- rake/lib/plugins_helper.rb
Picked changes with maven header auth support: https://github.com/applicaster/Zapp-Android/pull/2500
Original description:
Updated ruby zapp script to support Gradle HttpHeaderAuthentication for maven dependencies: https://docs.gradle.org/current/javadoc/org/gradle/authentication/http/HttpHeaderAuthentication.html
Expected format for maven dependency that should be included in root build.gradle file as result of script execution:
maven {
url "https://sample-url-to-maven-repo"
credentials(HttpHeaderCredentials) {
name = 'Sample-Name'
value = 'Sample-Value'
}
authentication {
header(HttpHeaderAuthentication)
}
}
Where maven repo url, header credentials name and header credentials value should be inflated based on optional plugin.manifest fields for new object header_credentials in existing …
> Feat maven header auth - merge from native SDK

- .circleci/config.yml
Now we upload to S3 before MS AppCenter
> feat: Upload to S3 before AppCenter

- .circleci/config.yml
- fastlane/Fastfile
- rake/templates/s3_apk.html.erb
-This PR is a new version of the download apk HTML.
It also simplifies the code a bit by setting a global (per step) env var `build_type`.
To run locally:
1. Set env vars - 
S3_BUCKET_NAME=assets-development.applicaster.com
AWS_ACCESS_KEY_ID=<dev access>
AWS_REGION=us-east-1
AWS_SECRET_ACCESS_KEY=<dev secret>
build_type=debug
2. Build the project
3. run `bundle exec fastlane s3_upload`
On Android device:
On non android device (desktop browser, iphone, etc):
> feat(apk download artificat): update s3 html template

- fastlane/Fastfile
- rake/templates/s3_apk.html.erb
- Using fastlane consts on s3 upload
- Use cdn url instead of bucket
> fix(s3 artifacts): use fastlane consts

- gradle.properties
Upgrade Core SDK to 8.2.0: ReactNative Push manager bridge added
> feat: upgrade core SDK to 8.2.0 (RN PushManagerBridge)

- android_quickbrick_app/src/main/java/com/applicaster/ui/application/BaseApplication.java
- gradle.properties
Upgrade Core SDK to 8.3.1 and connect Encrypted LocalStorage
> feat: upgrade Core SDK to 8.3.1 and connect Encrypted LocalStorage

- android_quickbrick_app/src/main/java/com/applicaster/ui/activities/MainActivity.kt
- android_quickbrick_app/src/main/java/com/applicaster/ui/interfaces/IUILayerManager.java
- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/QuickBrickManager.java
- rake/templates/qb_build.gradle.erb
Adding missing stuff required by OAuth2 plugin.
> Feat: oauth2 bridging

- android_quickbrick_app/build.gradle
Removed MS Appcenter Distribution dependency (was not used anyway)
> feat: remove MS Appcenter Distribution

- rake/lib/template_helper.rb
- spec/lib/template_helper_spec.rb
Upgrade QuickBrick SDK to 4.1.6
> feat: upgrade QuickBrick SDK to 4.1.6

- CHANGELOG.md
> feat: Changelog for 3.0.0

- rake/lib/template_helper.rb
- spec/lib/template_helper_spec.rb
This PR updates the repo to use Quick Brick 5.0.0
> chore: update to QB 5

- CHANGELOG.md
> feat: 4.0.0 changelog

- gradle.properties
player_overlay rn plugin type added
https://github.com/applicaster/applicaster-android-sdk/pull/1464
> feat: upgrade Applicaster Android SDK Core to 8.3.2

- CHANGELOG.md
> Feat changelog 5.0.0

- rake/templates/package.json.erb
This PR adds module resolution to make sure the webview native module is resolved to the proper version
> fix: add webview module resolution

- gradle.properties
Update CoreSDK to support new RN plugin type Purchases
> feat: Upgrade CoreSDK to 8.3.3

- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/QuickBrickManager.java
- gradle.properties
Log network calls made from react-native.
> feat: log network calls from react-native

- android_quickbrick_app/build.gradle
- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/QuickBrickManager.java
- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/ReactPackagesManager.java
- rake/templates/package.json.erb
- rake/templates/qb_build.gradle.erb
- rake/templates/qb_settings.gradle.erb
- spec/fixtures/files/qb_external_projects_settings.gradle
This PR is adding the RN gesture handler library
this is following the recommendation from https://docs.swmansion.com/react-native-gesture-handler/docs/#updating-mainactivityjava to use the provided wrapper for the react root view
the dependencies should be declared properly, but I'm not 100% sure about the addition to the gradle files
> feat: add-rn-gesture-handler-lib

- android_quickbrick_app/build.gradle
- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/ReactPackagesManager.java
- rake/templates/app_proguard-rules.pro
- rake/templates/package.json.erb
- rake/templates/qb_settings.gradle.erb
- spec/fixtures/files/qb_external_projects_settings.gradle
This PR adds the react-native-safe-area-context library, used in expo and many other RN apps, to provide reliable info on safe areas 
https://github.com/th3rdwave/react-native-safe-area-context
> feat: add safe area context lib

- android_quickbrick_app/src/main/java/com/applicaster/ui/quickbrick/QuickBrickManager.java
This PR fixes the scaling issue observed on android Tv, by using  the standard ReactRootView on TV, and the one provided by the gesture handler library on mobile
> fix: fix scaling issue on RN gesture integration

- gradle.properties
Upgrading Applicaster Android SDK Core to 8.3.5:
- push bridge fixes
- analytics logging improvements
- SessionStorage RN API improvement (`removeItem` added)
> feat: bump applicaster_android_sdk_core_version to 8.3.5

- .env
- .env.test
- android_quickbrick_app/src/main/java/com/applicaster/ui/application/BaseApplication.java
- gradle.properties
- rake/lib/template_helper.rb
- rake/templates/applicaster.properties.erb
- spec/fixtures/files/applicaster.properties
- Bumping SDK Core to 8.3.6
- Adding locale setup flow from https://github.com/applicaster/applicaster-android-sdk/pull/1473
> Feat: localization support

- gradle.properties
Bump Applicaster Android SDK Core version to 8.3.7
- Data loader fixes
> feat: bump applicaster-sdk-core to 8.3.7

- rake/lib/template_helper.rb
- spec/lib/template_helper_spec.rb
> feat: upgrade to QB 5.1.0

- rake/templates/qb_build.gradle.erb
Sometimes there is merge conflict on build, add this file to other META-INF/* ignored ones.
> fix: add annotation-experimental_release.kotlin_module to ignored

- CHANGELOG.md
> feat: Changelog 6.0.0

- gradle.properties
bump applicaster_android_sdk_core_version to 8.3.9 (plugin initialization order fix)
> feat: bump applicaster_android_sdk_core_version to 8.3.9

- rake/templates/gradle-wrapper.properties.erb
- rake/templates/qb_top_level_build.gradle.erb
Migrate from Bintray maven to S3 hosted one.
> feat: S3 maven migration

- gradle.properties
Bump applicaster_android_sdk_core_version to 8.3.10: Storage RN bridges fixes.
> feat: bump applicaster_android_sdk_core_version to 8.3.10

- CHANGELOG.md
> feat: changelog 7.0.0
